import {Dimensions} from 'react-native';
import {StyleSheet} from 'react-native';
import autoMergeLevel1 from 'redux-persist/es/stateReconciler/autoMergeLevel1';
import {
  WHITE,
  PURPLE,
  GRAY_300,
  ROTA_SHIFT,
  GRAY_400,
  ERR_COLOR_800,
  ROTA_AVAILABLE,
  STRONG_LIME,
  GRAY_200,
  GRAY_100,
  ERR_COLOR,
} from '../../assets/Colors';

export const styles = StyleSheet.create({
  container: {
    backgroundColor:'#abb8c3', 
    width:'100%', 
    height:'100%', 
    borderRadius:9
  },
  textTouchable:{
    flex:1,
    flexDirection:'row',
    justifyContent:'space-between',
    marginTop:10,
    },
  textSummary:{
    width:75,
    height:40,
    color:'#3f51b5',
    borderWidth:1,
    borderColor:'#673ab7',
    borderRadius:50,
    justifyContent:'center',
    alignItems:'center',
    padding:8,
    paddingLeft:1, 
  },
  textAction:{
    width:70,
    height:40,
    color:'#3f51b5',
    borderWidth:1,
    borderColor:'#673ab7',
    borderRadius:50,
    justifyContent:'center',
    alignItems:'center',
    padding:9,
    paddingLeft:13,
  },
  textNote:{
    width:70,
    height:40,
    color:'#3f51b5',
    borderWidth:1,
    borderColor:'#673ab7',
    borderRadius:50,
    justifyContent:'center',
    alignItems:'center',
    padding:9,
    paddingLeft:14,
  },
  textTask:{
    width:70,
    height:40,
    color:'#3f51b5',
    borderWidth:1,
    borderColor:'#673ab7',
    borderRadius:50,
    justifyContent:'center',
    alignItems:'center',
    padding:9,
    paddingLeft:15,
    },
  textsize:{
    fontSize:13,
    fontWeight:'bold',
  },
  task:{backgroundColor:'#673ab7'},
  popupHeader:{
    borderStyle: 'solid',
    borderColor: 'lightgrey',
    borderWidth:1,
    borderRadius:8,
    padding: 8,
    width:'100%',
    height:140,
    },
  
  textattendedview:{
    flexDirection:'row',
    fontSize:15,
    justifyContent:'space-between',
  },
  textemployee:{
    flexDirection:'row',
    justifyContent:'space-between',
    fontSize:30,
    fontWeight:'bold',
    color:'#1a237e',
  },
  buttonInfo:{
    width:50,
    height:30,
    color:'#1a237e',
    borderWidth:1,
    borderColor:'#ccc',
    backgroundColor:'#b3b3b3',
    borderRadius:4,
    padding:4,
    paddingLeft:10,
    position:'absolute',
    right:2,
    fontWeight:'bold',
    },
    buttonNote:{
      width:50,
      height:30,
      color:'#1a237e',
      borderWidth:1,
      borderColor:'#ccc',
      backgroundColor:'#b3b3b3',
      borderRadius:4,
      fontWeight:'bold',
      padding:4,
      paddingLeft:8,
      position:'absolute',
      right:2,
      marginTop:31,
      },
      buttonStyle: {
        backgroundColor: '#307ecc',
        borderWidth: 0,
        color: '#FFFFFF',
        borderColor: '#307ecc',
        height: 40,
        alignItems: 'center',
        borderRadius: 30,
        marginLeft: 35,
        marginRight: 35,
      },
      buttonTextStyle: {
        color: '#FFFFFF',
        paddingVertical: 10,
        fontSize: 16,
      },
      textStyle: {
        backgroundColor: '#fff',
        fontSize: 15,
        marginTop: 16,
        marginLeft: 35,
        marginRight: 35,
        textAlign: 'center',
      },
  textModalException: {
    fontSize: 18,
    marginTop: 25,
    marginBottom: 25,
    textAlign: 'center',
  },
  textModalColor: {
    fontSize: 18,
    color: ERR_COLOR,
    fontWeight: 'bold',
  },
  nameSection: {
    height: '18%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nameStyle: {
    width:'53.3%',
    paddingLeft:20,
  },
  textName: {
    fontSize: 20,
    fontWeight: 'bold',
    color:'#1a237e',
  },
  dobStyle: {
    fontWeight:'bold',
    color: GRAY_400,
  },
  visitNumber: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  dateStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  weightStyle: {
    fontWeight: 'bold',
  },
  textStyle: {
    fontSize: 12,
    marginLeft: 15,
  },
  buttonsView: {
    height: '14%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  buttonContacts: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: PURPLE,
    width: '47%',
    height: '70%',
  },
  buttonCall: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: STRONG_LIME,
    width: '47%',
    height: '70%',
  },
  iconContacts: {
    fontSize: 20,
    color: PURPLE,
  },
  iconTelephone: {
    fontSize: 23,
    color: STRONG_LIME,
  },
  instructionsComponent: {
    height: '80%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  iconBook: {
    fontSize: 20,
    color: PURPLE,
  },
  iconMarker: {
    fontSize: 21,
    color: PURPLE,
  },
  viewIcon: {
    width: '6%',
  },
  addressContainer: {
    width: '60%',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  instructions: {
    flexDirection: 'row',
    backgroundColor: GRAY_200,
    borderRadius: 12,
    width: '92%',
    maxWidth: '92%',
    height: '100%',
    padding: 8,
  },
  buttonClockIn: {
    flexDirection: 'row',
    backgroundColor: STRONG_LIME,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    width: 180,
    marginRight: 10,
    paddingTop: 14,
    paddingBottom: 14,
  },
  buttonClockOut: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: 'solid',
    borderColor: ERR_COLOR,
    width: 180,
    marginLeft: 10,
    paddingTop: 14,
    paddingBottom: 14,
  },
  returnIcon: {
    fontSize: 25,
  },
  textStyleReturn: {
    fontSize: 18,
    marginLeft: 8,
  },
  textClockIn: {
    color: WHITE,
  },
  textClockOut: {
    color: ERR_COLOR,
  },
  map: {
    width: '100%',
    height: '100%',
  },
  addressView: {
    marginTop: 10,
    marginBottom: 10,
  },
  gradientStyle: {
    padding: 3,
    borderRadius: 50,
  },
  pictureIconView: {
    width: 70,
    height: 70,
    backgroundColor: GRAY_200,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pictureIcon: {
    fontSize: 30,
    color: PURPLE,
  },
  photo: {
    width: 70,
    height: 70,
    borderRadius: 50,
  },
  viewImageLogo: {
    width: 55,
    height: 55,
    borderRadius: 35,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  myLogo: {
    width: 35,
    height: 35,
  },
  viewDetails: {
    height: '10%',
    flexDirection: 'column',
  },
  viewCallAndContact: {
    height: '12%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingLeft: '7%',
    paddingRight: '7%',
  },
  viewInstructions: {
    height: '20%',
    paddingBottom: 5,
    flexDirection: 'column',
    justifyContent: 'space-between',
  },
  viewTextInstructions: {
    height: '10%',
  },
  viewAddress: {
    height: '26%',
    flexDirection: 'column',
    justifyContent: 'space-between',
    paddingBottom: 5,
  },
  viewTextAddress: {
    //height: '10%',
    width:'90%',
    display:'flex',
    flexDirection: 'row',
    justifyContent:'space-between'
  },
});

export const styleConstructor = (currentData, isClockOnHold) => {
  let style = {
    clockIn: {
      flexDirection: 'row',
      backgroundColor: STRONG_LIME,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 12,
      width: '48%',
      height: '75%',
      opacity:
        (currentData && currentData.actual_visit_start_time) ||
        isClockOnHold.clockIn
          ? 0.4
          : 1,
    },
    clockOut: {
      flexDirection: 'row',
      backgroundColor: 'transparent',
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 12,
      borderWidth: 1,
      borderStyle: 'solid',
      borderColor: ERR_COLOR,
      width: '48%',
      height: '75%',
      opacity: 1,
    },
  };

  return StyleSheet.create(style);
};
